### ISSUE TITLE
preserving ticket numbers

### ISSUE THREAD

**Issue by glensc** [moimael/trac-to-gitlab#1]
i was looking for trac to gitlab converter so the ticket references in commit messages would map to proper ticket

but this converter (api mode) creates the ticket in some random order.

also in trac i had multiple svn projects relating to single trac instance, while in gitlab i have each of those git projects as separate gitlab projects, so i would need to filter out what tickets to import (by component name perhaps, or just manual listing. i have ~120 tickets i want to preserve historically

**Comment by moimael** [comment]
I'm not actively maintaining this, since it was improved and used for a one off migration. I accept pull requests though ;)

**Comment by glensc** [comment]
solved partially with #5
