### ISSUE TITLE
"Labels" not properly migrated

### ISSUE THREAD

**Issue by phatpaul** [moimael/trac-to-gitlab#14]
The script worked great allowing me to migrate from Trac 0.11.7 to Gitlab 8.14.1.  
All the issues and wiki migrated ok.

But now that I'm using Gitlab, the "Labels" that were transferred from Trac to Gitlab seem to be in a weird state.
They show up in the existing issue list, but I can't assign those labels to any new issues.  Also, they don't show up in the list of Labels for the project.
If I try to create a new label with the same name it gives an error "Title has already been taken".

**Comment by phatpaul** [comment]
I learned some more.  
If I add any new labels within Gitlab UI, then I am unable to access any previously migrated issues.   When I try to open any migrated issue, I get a error: "500 Whoops, something went wrong on our end."

This is even more of a problem than not being able to use existing labels.

**Comment by phatpaul** [comment]
Oops, closed this issue by accident.  Reopened.

**Comment by moimael** [comment]
I'm not actively maintaining this, since it was improved and used for a one off migration. I accept pull requests though ;)

**Comment by slovdahl** [comment]
Maybe #17 solves this issue?

**Comment by moimael** [comment]
@phatpaul Can you have a look now that it is merged ?

**Comment by ePirat** [comment]
I think this is fixed.
