### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by nazavode** [moimael/trac-to-gitlab#23]
Hi, I would like to thank you for all the inspiration that this project gave me. In the near future I'm going to face the problem of migrating a *lot* (hundreds) of Trac instances over to GitLab and in the attempt to make the trac-to-gitlab code more easy to automate I think I went too far with the cleanup and refactoring process., so I decided to switch over to a brand new project, actually keeping the trac-to-gitlab refactored code as the core data extraction and migration logic.  You can find the project here:

https://github.com/nazavode/tracboat

I gave it the form of a command line tool, with subcommands (a la git) and the ability to export a Trac project to a local file (in multiple human readable formats) and to migrate (a previously exported project or directly from Trac) to a mock GitLab instance (into a SQLite database) just to be able to inspect it before the actual migration in production. I kept the GPLv3 because I think I had to inherit it to be compliant and I mentioned you in the credits (in the README.rst and in the AUTHORS file as well). If you think that someone else should be mentioned please let me know or just open a pull request. Of course, code reviews, issues and pull requests are *highly* appreciated!

Thank you again!

**Comment by nazavode** [comment]
Oh, I forgot to mention @slovdahl as well, this project started from his fork actually.

**Comment by moimael** [comment]
Hi ! Happy you found the project useful and that you made it into something cleaner :) !

To be fair, if you look at this project README, I'm not the one who started the project, I merely put it on Github and fixed bugs to be able to use it with our own trac instance.

Thanks for your work :)

**Comment by nazavode** [comment]
Hi! So, I tried to gather some more names, I found:

- Jens Neuhalfen @neuhalje 
- @tcchau (https://github.com/tcchau) of whom I cannot guess the real name

My [AUTHORS](https://github.com/nazavode/tracboat/blob/master/AUTHORS) file contains already some credits I found in comments throughout the code base, I'm gonna add these two as well!

**Comment by neuhalje** [comment]
Very good idea! Thanks for mentioning me!

**Comment by tcchau** [comment]
Hi there,

I don't recall my participation in this project but sure, thanks for the
mention!

clinton.chau@utoronto.ca

**Comment by nazavode** [comment]
@tcchau I found your username in a gist with a snippet used by some other author (@neuhalje maybe?).

**Comment by neuhalje** [comment]
I guess my contribution stems from https://github.com/neuhalje/hack-copy-track-issues-to-gitlab which has been forked several times.

**Comment by moimael** [comment]
@nazavode Do you plan on maintaining tracboat for the foreseeable future ?

Because if that's the case, i'd happily amend the README to mark this project as deprecated and redirect to yours.
I don't have any interest maintaining this anymore since our Trac to Gitlab migration was successful. Also has tracboat feature parity with trac-to-gitlab ? (I guess so but I just want to be sure :))

**Comment by neuhalje** [comment]
@moimael / @nazavode same for mine

**Comment by nazavode** [comment]
@moimael, sorry for the hiatus but in the past months I've had so little time. Anyway, yes my plan is to maintain this project in the long run and again yes, my plan is to integrate all of the trac-to-gitlab features.

**Comment by glensc** [comment]
tracboat got my improvements when @nazavode had no longer time

i've successfully migrated few dozen projects and i've added pretty much all features i had in my trac enabled (timetracking, comment linking, attachemnt linking): https://github.com/tracboat/tracboat/pull/48

so there, there https://github.com/moimael/trac-to-gitlab/pull/32

**Comment by PhilippWendler** [comment]
It seems that tracboat still does not support using the API of a GitLab instance, right? At least, there is an [open issue](https://github.com/tracboat/tracboat/issues/5).
This means that all users who want to migrate to GitLab.com cannot use it and need to keep using trac-to-gitlab.
Maybe you want to add this information to the readme?

**Comment by moimael** [comment]
If anyone is willing to take ownership of this repo, I'll gladly transfer it. I have no time/interest in maintaining this project anymore.

**Comment by glensc** [comment]
@moimael I have no personal interest as well, but I may help to deal with issues. you can add me as maintainer/developer for that.

I have https://github.com/tracboat/tracboat at same state (which is actually @nazavode project originally). no more personal interest as projects I needed are migrated.
