### ISSUE TITLE
can't get direct mode to work with postgres

### ISSUE THREAD

**Issue by andrew-schulman** [moimael/trac-to-gitlab#27]
I'm using the [Bitnami Gitlab CE image](https://bitnami.com/stack/gitlab), which runs Gitlab on PostgreSQL. I can import from Trac to there fine using the API mode, but as is documented in the README, that doesn't import attachments, issue owners, or issue dates. So I want to use direct mode instead.

So far I can't get it to work. No matter what settings I use, when I run migrate.py I get `Peer authentication failed for user "gitlab"` (or `for user "bitnami"`, etc.). The instructions for direct mode in migrate.cfg say:

> You need to create a PostgreSQL user for the user that runs the migration and map it to the gitlab user in /var/opt/gitlab/postgresql/data/pg_ident.conf

I've tried many permutations of this, setting variations of lines like

    gitlab bitnami postgres

in /var/opt/gitlab/postgresql/data/pg_ident.conf, and restarting Postgres (`/opt/bitnami/ctlscript.sh restart postgresql`). Still I get `Peer authentication failed`.

I guess I'm confused about who exactly "the user that runs the migration" (presumably me, user bitnami) and "the gitlab user" are. Further guidance and examples would really help here.

Thank you.

**Comment by gehlert** [comment]
Just in case this may be still helpful to others:

I had the same issue. For me, the following line in `/var/opt/gitlab/postgresql/data/pg_ident.conf` fixes the problem:

```
gitlab bitnami gitlab
```

Nevertheless, I can't get the importing of attachments working in direct mode (Gitlab 9.0.12).
