### ISSUE TITLE
Error while importing issues from trac to gitlab with API version v4

### ISSUE THREAD

**Issue by miftner** [moimael/trac-to-gitlab#31]
While migrating my trac issues to gitlab isung the gitlab v4 api i encountered an error regarding the Ticket ids.
Gitlab uses two parameters, id für global ticket count and iid for project-specific ticket count.

Because of that the line 109 in the Connection.py file should be altered as follow:
` new_ticket_id  = new_ticket["id"]`
should be replaced by
` new_ticket_iid  = new_ticket["iid"]`

**Comment by glensc** [comment]
btw: https://github.com/moimael/trac-to-gitlab/pull/32
