### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by kerrhome** [moimael/trac-to-gitlab#33]
I ran the users.sh and I'm only getting to ticket #3735 out of 18,000+ tickets.  I assume there is a character in the changelog that the xml parser doesn't like.  When I Googled the error, I see that many times it's a '&' that xml parsers dislike, but I have none of those. I do see a ' < ' in one comment (surrounded by a single whitespace on both sides).  I scoured documentation here and with tracboat and see no mention of xml parsing errors or how to handle them.
 
```
........
ticket id: 3733
ticket index: 3732
owner: joeschmo3
reporter: joeschmo2
ticket message poster:  joeschmo1
ticket message poster:  joeschmo2
ticket message poster:  joeschmo1
ticket id: 3734
ticket index: 3733
owner: joeschmo3
reporter: joeschmo2
ticket message poster:  joeschmo1
ticket message poster:  joeschmo2
ticket id: 3735
ticket index: 3734
owner: joeschmo4
reporter: joeschmo4
Traceback (most recent call last):
  File "./collect-users.py", line 127, in <module>
    collect_users(source)
  File "./collect-users.py", line 98, in collect_users
    changelog = source.ticket.changeLog(src_ticket_id)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1487, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 152, column 97
```

Additional question: does trac_to_git look only at the current state of changelog entries or does it also look at previous versions of modified changelog comments? If it's the latter, that's a bit more painful for debugging.

**Comment by glensc** [comment]
heh, you got same problem in both projects https://github.com/tracboat/tracboat/issues/59 :)

**Comment by kerrhome** [comment]
Yes I do.  Since I'm blocked with both tools, I thought I'd report it in both.  I can close one if it is not useful.

**Comment by glensc** [comment]
nah, it just proofs the problem is in the underlying [tracxmlrpc] library.

try to make pure test, using only the library, and don't forget to include version detail.

[tracxmlrpc]: https://trac-hacks.org/wiki/XmlRpcPlugin

**Comment by kerrhome** [comment]
See https://github.com/tracboat/tracboat/issues/59#issuecomment-468364886
